CREATE TABLE customer1 (
    cust_id INT PRIMARY KEY,
    name VARCHAR(100),
    city VARCHAR(100),
    country VARCHAR(100)
);

INSERT INTO customer1 (cust_id, name, city, country)VALUES (1, 'John Doe', 'Ahmedabad', 'India');
INSERT INTO customer1 (cust_id, name, city, country)VALUES (2, 'Alice Smith', 'New York', 'USA');
INSERT INTO customer1 (cust_id, name, city, country)VALUES (3, 'Bob Brown', 'London', 'UK');
INSERT INTO customer1 (cust_id, name, city, country)VALUES (4, 'Charlie Black', 'Ahmedabad', 'India');
