CREATE TABLE ENROLL (
    rollno NUMBER,
    courseno VARCHAR2(10),
    Earn_Credit NUMBER,
    FOREIGN KEY (rollno) REFERENCES STUDENT(rollno),
    FOREIGN KEY (courseno) REFERENCES COURSE(C_No)
);

INSERT INTO ENROLL VALUES (11, 'C101', 4);
INSERT INTO ENROLL VALUES (11, 'C102', 3);
INSERT INTO ENROLL VALUES (12, 'C101', 4);
INSERT INTO ENROLL VALUES (12, 'C103', 4);
INSERT INTO ENROLL VALUES (13, 'C103', 4);
INSERT INTO ENROLL VALUES (11, 'C103', 2);
INSERT INTO ENROLL VALUES (11, 'C104', 3);