CREATE TABLE STUDENT (
    rollno NUMBER PRIMARY KEY,
    fname VARCHAR2(50),
    lname VARCHAR2(50),
    dob DATE
);

INSERT INTO STUDENT VALUES (11, 'Kapil', 'Sharma', TO_DATE('2003-01-01', 'YYYY-MM-DD'));
INSERT INTO STUDENT VALUES (12, 'Anjali', 'Verma', TO_DATE('2002-06-21', 'YYYY-MM-DD'));
INSERT INTO STUDENT VALUES (13, 'Ravi', 'Kumar', TO_DATE('2004-03-12', 'YYYY-MM-DD'));
INSERT INTO STUDENT VALUES (14, 'Pooja', 'Singh', TO_DATE('2001-11-23', 'YYYY-MM-DD'));
