CREATE OR REPLACE FUNCTION ASS4_3
(FDEPTNO IN EMP.DEPTNO%TYPE,FSAL IN EMP.SAL%TYPE)
RETURN NUMBER AS
BONUS NUMBER;

BEGIN
	IF FDEPTNO=10 THEN
		BONUS := FSAL*0.05;
	ELSIF FDEPTNO=20 THEN
		BONUS := FSAL*0.10;
	ELSIF FDEPTNO=30 THEN
		BONUS := FSAL*0.15;
	ELSE
		BONUS := FSAL*0.20;
	END IF;

	RETURN BONUS;
END;
/